ignore:
  - "apps/migrations"
  - "apps/admin.py"
  - "apps/forms.py"
  - "apps/filters.py"
  - "apps/inlines.py"
  - "apps/mixins.py"
  - "apps/models.py"
  - "apps/renderers.py"
  - "apps/styles.py"
  - "apps/urls.py"
  - "apps/widgets.py"
  - "**/__init__.py"

coverage:
  range: 70..95
  round: down
  precision: 2
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        base: auto
