version: '3'

services:
  postgres:
    restart: unless-stopped
    image: postgres:12-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: stubborn_dev
      POSTGRES_USER: stubborn_dev
      POSTGRES_PASSWORD: notsecret

  django:
    restart: unless-stopped
    image: pysergio/stubborn:0.2.0-dev
    container_name: stubborn-django
    environment:
      DJANGO_SETTINGS_MODULE: stubborn.settings.staging
    env_file:
      - .env.staging
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    links:
      - postgres

volumes:
  pg_data:
