version: '3'

services:
  postgres:
    restart: unless-stopped
    image: postgres:12-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: stubborn_test
      POSTGRES_USER: stubborn_test
      POSTGRES_PASSWORD: postgres

  django:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    container_name: stubborn-django
    environment:
      DJANGO_SETTINGS_MODULE: stubborn.settings.test
      DATABASE_URL: postgres://stubborn_test:postgres@postgres:5432/stubborn_test
      SECRET_KEY: test
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    links:
      - postgres

volumes:
  pg_data:
