# Generated by Django 3.2.6 on 2021-11-02 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='Slug')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Application Owner')),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
            },
        ),
        migrations.CreateModel(
            name='ResponseStub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.PositiveSmallIntegerField(verbose_name='Status code')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='Headers')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Response Body')),
                ('description', models.CharField(blank=True, max_length=30, null=True, verbose_name='Short Description')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='apps.application')),
            ],
            options={
                'verbose_name': 'response',
                'verbose_name_plural': 'responses',
            },
        ),
        migrations.CreateModel(
            name='ResourceStub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.SlugField(allow_unicode=True, verbose_name='URI')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('timeout', models.PositiveSmallIntegerField(default=0, verbose_name='Response Timeout')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10, verbose_name='HTTP Method')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='apps.application')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='apps.responsestub', verbose_name='Response')),
            ],
            options={
                'verbose_name': 'resource',
                'verbose_name_plural': 'resources',
                'unique_together': {('uri', 'description')},
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.JSONField(blank=True, default=dict, null=True, verbose_name='Query Params')),
                ('body', models.JSONField(blank=True, default=dict, null=True, verbose_name='Request Body')),
                ('headers', models.JSONField(blank=True, default=dict, null=True, verbose_name='Headers')),
                ('ipaddress', models.GenericIPAddressField(default='127.0.0.1', verbose_name='Remote IP')),
                ('x_real_ip', models.GenericIPAddressField(blank=True, default='127.0.0.1', null=True, verbose_name='X-REAL-IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Received at')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='apps.application')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='apps.resourcestub')),
                ('response', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.responsestub', verbose_name='Response')),
            ],
            options={
                'verbose_name': 'request log',
                'verbose_name_plural': 'request logs',
            },
        ),
    ]
