# Generated by Django 3.2.6 on 2021-11-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20211102_2006'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resourcestub',
            unique_together={('uri', 'response')},
        ),
    ]
