# Generated by Django 3.2.6 on 2021-11-04 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_resourcestub_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resourcestub',
            unique_together={('uri', 'method')},
        ),
    ]
