# Generated by Django 3.2.11 on 2022-02-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20220107_1814_squashed_0008_alter_responsestub_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcestub',
            name='Proxy to',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
