# Generated by Django 3.2.11 on 2022-03-28 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_auto_20220326_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcestub',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='apps.responsestub', verbose_name='Response'),
        ),
    ]
