# Generated by Django 3.2.11 on 2022-04-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_alter_resourcestub_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='method',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='resourcestub',
            name='method',
            field=models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], default='GET', max_length=10, null=True, verbose_name='HTTP Method'),
        ),
    ]
