# Generated by Django 3.2.13 on 2022-04-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_auto_20220424_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='URL Called'),
        ),
    ]
