# Generated by Django 3.2.13 on 2022-06-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_auto_20220601_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcestub',
            name='response_type',
            field=models.CharField(choices=[('CUSTOM', 'Custom Response'), ('PROXY_CURRENT', 'Proxy Specific URL'), ('PROXY_GLOBAL', 'Global Proxy')], default='CUSTOM', max_length=30),
        ),
    ]
