# Generated by Django 3.2.13 on 2022-06-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_alter_resourcestub_response_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcestub',
            old_name='uri',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='resourcestub',
            name='response_type',
            field=models.CharField(choices=[('CUSTOM', 'Custom Response'), ('PROXY_CURRENT', 'Proxy Specific URL'), ('PROXY_GLOBAL', 'Global Proxy')], default='CUSTOM', max_length=30, verbose_name='Response Type'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcestub',
            unique_together={('slug', 'method')},
        ),
    ]
