# Generated by Django 3.2.16 on 2022-12-26 21:44
import uuid

from django.db import migrations


def populate_uuid_fields(apps, schema_editor):
    for table in ('Application', 'RequestStub', 'ResourceHook', 'ResourceStub', 'ResponseStub', 'RequestLog'):
        model = apps.get_model('apps', table)
        for record in model.objects.all():
            record.alter_id = uuid.uuid4()
            record.save(update_fields=('alter_id',))


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_auto_20221226_2144'),
    ]

    operations = [
        migrations.RunPython(populate_uuid_fields)
    ]
