# Generated by Django 3.2.16 on 2022-12-26 22:42

from django.db import migrations, models
import django.db.models.deletion


def set_new_relationship(record):
    fields = ('application', 'resource', 'response', 'request')
    for field in fields:
        if related_record := getattr(record, field, None):
            setattr(record, f'{field}_uuid', related_record)
    record.save()


def populate_relationship_fields(apps, schema_editor):
    for table in ('RequestStub', 'ResourceHook', 'ResourceStub', 'ResponseStub', 'RequestLog'):
        model = apps.get_model('apps', table)
        for record in model.objects.all():
            set_new_relationship(record)


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_auto_20221226_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='application_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_uuid', to='apps.application', to_field='alter_id'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='resource_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_uuid', to='apps.resourcestub', to_field='alter_id'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='response_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_uuid', to='apps.responsestub', to_field='alter_id', verbose_name='Response'),
        ),
        migrations.AddField(
            model_name='requeststub',
            name='application_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_uuid', to='apps.application', to_field='alter_id'),
        ),
        migrations.AddField(
            model_name='resourcehook',
            name='request_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hooks_uuid', to='apps.requeststub', to_field='alter_id'),
        ),
        migrations.AddField(
            model_name='resourcehook',
            name='resource_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hooks_uuid', to='apps.resourcestub', to_field='alter_id'),
        ),
        migrations.AddField(
            model_name='resourcestub',
            name='application_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources_uuid', to='apps.application', to_field='alter_id'),
        ),
        migrations.AddField(
            model_name='resourcestub',
            name='response_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources_uuid', to='apps.responsestub', to_field='alter_id', verbose_name='Response'),
        ),
        migrations.AddField(
            model_name='responsestub',
            name='application_uuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses_uuid', to='apps.application', to_field='alter_id'),
        ),
        migrations.RunPython(populate_relationship_fields)
    ]
