# Generated by Django 3.2.16 on 2022-12-26 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0028_remove_resourcehook_unique_order_per_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='application_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_uuid', to='apps.application', to_field='alter_id'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='resource_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_uuid', to='apps.resourcestub', to_field='alter_id'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='response_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_uuid', to='apps.responsestub', to_field='alter_id', verbose_name='Response'),
        ),
        migrations.AlterField(
            model_name='requeststub',
            name='application_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_uuid', to='apps.application', to_field='alter_id'),
        ),
        migrations.AlterField(
            model_name='resourcehook',
            name='request_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hooks_uuid', to='apps.requeststub', to_field='alter_id'),
        ),
        migrations.AlterField(
            model_name='resourcehook',
            name='resource_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hooks_uuid', to='apps.resourcestub', to_field='alter_id'),
        ),
        migrations.AlterField(
            model_name='resourcestub',
            name='application_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources_uuid', to='apps.application', to_field='alter_id'),
        ),
        migrations.AlterField(
            model_name='resourcestub',
            name='response_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources_uuid', to='apps.responsestub', to_field='alter_id', verbose_name='Response'),
        ),
        migrations.AlterField(
            model_name='responsestub',
            name='application_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses_uuid', to='apps.application', to_field='alter_id'),
        ),
    ]
