# Generated by Django 3.2.16 on 2022-12-26 23:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_auto_20221226_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='id',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='id',
        ),
        migrations.RemoveField(
            model_name='requeststub',
            name='id',
        ),
        migrations.RemoveField(
            model_name='resourcehook',
            name='id',
        ),
        migrations.RemoveField(
            model_name='resourcestub',
            name='id',
        ),
        migrations.RemoveField(
            model_name='responsestub',
            name='id',
        ),
        migrations.AlterField(
            model_name='application',
            name='alter_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='alter_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requeststub',
            name='alter_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resourcehook',
            name='alter_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resourcestub',
            name='alter_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='responsestub',
            name='alter_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
