# Generated by Django 3.2.16 on 2022-12-26 23:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0031_auto_20221226_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='application_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_uuid', to='apps.application'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='resource_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_uuid', to='apps.resourcestub'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='response_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_uuid', to='apps.responsestub', verbose_name='Response'),
        ),
        migrations.AlterField(
            model_name='requeststub',
            name='application_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_uuid', to='apps.application'),
        ),
        migrations.AlterField(
            model_name='resourcehook',
            name='request_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hooks_uuid', to='apps.requeststub'),
        ),
        migrations.AlterField(
            model_name='resourcehook',
            name='resource_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hooks_uuid', to='apps.resourcestub'),
        ),
        migrations.AlterField(
            model_name='resourcestub',
            name='application_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources_uuid', to='apps.application'),
        ),
        migrations.AlterField(
            model_name='resourcestub',
            name='response_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources_uuid', to='apps.responsestub', verbose_name='Response'),
        ),
        migrations.AlterField(
            model_name='responsestub',
            name='application_uuid',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses_uuid', to='apps.application'),
        ),
    ]

