# Generated by Django 3.2.16 on 2022-12-26 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0032_auto_20221226_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestlog',
            old_name='application_uuid',
            new_name='application',
        ),
        migrations.RenameField(
            model_name='requestlog',
            old_name='resource_uuid',
            new_name='resource',
        ),
        migrations.RenameField(
            model_name='requestlog',
            old_name='response_uuid',
            new_name='response',
        ),
        migrations.RenameField(
            model_name='requeststub',
            old_name='application_uuid',
            new_name='application',
        ),
        migrations.RenameField(
            model_name='resourcehook',
            old_name='request_uuid',
            new_name='request',
        ),
        migrations.RenameField(
            model_name='resourcehook',
            old_name='resource_uuid',
            new_name='resource',
        ),
        migrations.RenameField(
            model_name='resourcestub',
            old_name='application_uuid',
            new_name='application',
        ),
        migrations.RenameField(
            model_name='resourcestub',
            old_name='response_uuid',
            new_name='response',
        ),
        migrations.RenameField(
            model_name='responsestub',
            old_name='application_uuid',
            new_name='application',
        ),
    ]
