# Generated by Django 3.2.16 on 2022-12-26 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0033_auto_20221226_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='alter_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='requestlog',
            old_name='alter_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='requeststub',
            old_name='alter_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='resourcehook',
            old_name='alter_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='resourcestub',
            old_name='alter_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='responsestub',
            old_name='alter_id',
            new_name='id',
        ),
    ]
