# Generated by Django 3.2.16 on 2022-12-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0034_auto_20221226_2318'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='resourcehook',
            constraint=models.UniqueConstraint(fields=('order', 'lifecycle', 'resource'), name='unique_order_per_resource'),
        ),
    ]
