# Generated by Django 3.2.16 on 2022-12-28 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0037_auto_20221227_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcestub',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='apps.application'),
        ),
    ]
