# Generated by Django 3.2.16 on 2022-12-28 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0038_alter_resourcestub_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='apps.application'),
        ),
    ]
