# Generated by Django 3.2.16 on 2022-12-28 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0039_alter_requestlog_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsestub',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='apps.application'),
        ),
    ]
