# Generated by Django 3.2.18 on 2023-03-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0042_resourcestub_is_enabled'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resourcestub',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='resourcestub',
            constraint=models.UniqueConstraint(condition=models.Q(('is_enabled', True)), fields=('slug', 'method', 'tail'), name='unique_enabled_slug'),
        ),
    ]
