# Generated by Django 3.2.19 on 2023-09-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0043_auto_20230308_0119'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resourcestub',
            name='unique_enabled_slug',
        ),
        migrations.AddConstraint(
            model_name='resourcestub',
            constraint=models.UniqueConstraint(condition=models.Q(('is_enabled', True)), fields=('slug', 'method', 'tail', 'application'), name='unique_enabled_slug'),
        ),
    ]
