# Generated by Django 3.2.21 on 2023-10-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0044_auto_20230930_1116'),
        ('apps', '0044_resourcestub_inject_stubborn_headers'),
    ]

    operations = [
    ]
