# Generated by Django 3.2.19 on 2023-08-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0044_auto_20230930_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcestub',
            name='inject_stubborn_headers',
            field=models.BooleanField(default=False, verbose_name='Inject Stubborn Headers'),
        ),
    ]
