# Generated by Django 3.2.21 on 2023-10-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0045_merge_20231008_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=models.SlugField(allow_unicode=True, verbose_name='Slug'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('is_enabled', True)), fields=('slug', 'name'), name='app_unique_enabled_slug'),
        ),
    ]
