# Generated by Django 3.2.23 on 2024-04-19 11:27

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_alter_user_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0046_auto_20231008_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='Slug')),
                ('team_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10, verbose_name='Team Type')),
                ('inviter', models.CharField(choices=[('owner', 'Owner'), ('everybody', 'Everybody')], default='owner', max_length=10, verbose_name='Inviter')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Team Owner')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.CreateModel(
            name='StubUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('displayed_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Displayed name')),
                ('teams', models.ManyToManyField(related_name='users', to='apps.Team', verbose_name='teams')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_team_slug_per_owner'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('owner', 'slug')},
        ),
    ]
