# Generated by Django 3.2.23 on 2024-04-20 12:59

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0015_alter_user_email'),
        ('apps', '0046_auto_20231008_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('displayed_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Displayed name')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='Slug')),
                ('team_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10, verbose_name='Team Type')),
                ('inviter', models.CharField(choices=[('owner', 'Owner'), ('everybody', 'Everybody')], default='owner', max_length=10, verbose_name='Inviter')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='apps.member', verbose_name='Team Owner')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='teams',
            field=models.ManyToManyField(related_name='members', to='apps.Team', verbose_name='Teams'),
        ),
        migrations.AlterField(
            model_name='application',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='apps.member', verbose_name='Application Owner'),
        ),
        migrations.AlterField(
            model_name='requeststub',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='apps.member', verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='resourcestub',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='apps.member', verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='responsestub',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='apps.member', verbose_name='Created by'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_team_slug_per_owner'),
        ),
    ]
