# Generated by Django 3.2.23 on 2024-01-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0046_auto_20231008_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcestub',
            name='tail',
            field=models.CharField(blank=True, default='', max_length=2048, verbose_name='URL Tail'),
        ),
    ]
