# Generated by Django 3.2.23 on 2024-04-21 18:14

from django.db import migrations, models

def change_user_type(apps, schema_editor):
    content_type_model = apps.get_model('contenttypes', 'ContentType')
    content_type = content_type_model.objects.filter(
        app_label='auth',
        model='user'
    ).first()
    if content_type:
        content_type.app_label = 'user'
        content_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0047_auto_20240421_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RunPython(change_user_type),
    ]
