name: Quality Gate
on: push

jobs:
  Flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Flake8
        run: |
          pip install flake8 flake8-isort
      - name: Run Flake8
        run: |
          flake8
  Mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - uses: actions/checkout@v2
      - name: Install Deps
        run: |
          pip install -r requirements-dev.txt
      - name: Providing environment
        run: |
          ln .env.test stubborn/settings/.env
      - name: Run Mypy
        run: |
          mypy .
  PyTest:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: stubborn_test
          POSTGRES_USER: stubborn_test
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - uses: actions/checkout@v2
      - name: Install Deps
        run: |
          pip install -r requirements-dev.txt
      - name: Providing environment
        run: |
          ln .env.test stubborn/settings/.env
      - name: Run migrations
        run: |
          python manage.py migrate
      - name: Run PyTest
        run: |
          coverage run -m pytest
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
