name: Quality Gate
on: push
jobs:
  Flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Flake8
        run: |
          pip install flake8==4.0.1 flake8-isort==4.1.1
      - name: Run Flake8
        run: |
          flake8
  Mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Mypy
        run: |
          pip install mypy==0.910 django-stubs==1.9.0
      - name: Run Mypy
        run: |
          mypy .
